from __future__ import annotations
import csv, hashlib, json, subprocess
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB=ROOT/"datasets/mdc_ml_database_v1"
OUT=ROOT/"outputs/mdc_database_nominal_semantic_audit_v1"
REPORT=ROOT/"reports/mdc_defect_450/mdc_database_nominal_semantic_audit_v1.md"

def rows(name):
    with (DB/name).open(encoding="utf-8",newline="") as f:return list(csv.DictReader(f))
def count(rows_, key):return dict(sorted(Counter((r.get(key,"") if r.get(key,"")!="" else "<null>") for r in rows_).items()))
def write_csv(path, data, fields):
    with path.open("w",encoding="utf-8",newline="") as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(data)
def git(*args):return subprocess.check_output(["git",*args],cwd=ROOT,text=True,encoding="utf-8",errors="replace").strip()
def brief(r):
    keys=["geometry_id","geometry_hash","candidate_id_primary","candidate_aliases","topology_family","N","M","H_nm","L_nm","C_nm","added_defect_thickness_nm","effective_central_L_thickness_nm","physical_layer_count","total_thickness_nm","is_nominal_geometry","parent_nominal_geometry_id","provenance_count","quality_status"]
    return {k:r.get(k,"") for k in keys}

def main():
    manifest=json.loads((DB/"database_manifest.json").read_text(encoding="utf-8"));schema=json.loads((DB/"schema.json").read_text(encoding="utf-8"));split_audit=json.loads((DB/"split_audit.json").read_text(encoding="utf-8"));quality=json.loads((DB/"quality_audit.json").read_text(encoding="utf-8"))
    geo=rows("geometry_master.csv");tmm=rows("tmm_nominal_metrics.csv");tol=rows("tolerance_samples.csv");fdtd=rows("fdtd_validation.csv");spl=rows("split_assignments.csv");prov=rows("provenance_links.csv");labels=rows("label_dictionary.csv")
    by_gid={r["geometry_id"]:r for r in geo};geo_hashes={r["geometry_hash"] for r in geo};tmm_hashes={r["geometry_hash"] for r in tmm};tol_hashes={r["geometry_hash"] for r in tol};fdtd_hashes={r["geometry_hash"] for r in fdtd}
    tmm_by_gid={r["geometry_id"]:r for r in tmm};split_by_record={r["record_id"]:r for r in spl}
    joined=[]
    for r in tmm:
        g=by_gid.get(r["geometry_id"],{});s=split_by_record.get(r["record_id"],{})
        joined.append({"record_id":r["record_id"],"geometry_id":r["geometry_id"],"geometry_hash":r["geometry_hash"],"hash_join_status":"matched" if r["geometry_hash"] in geo_hashes else "missing_geometry_hash","id_join_status":"matched" if g else "missing_geometry_id","tmm_source_id":r.get("source_id",""),"tmm_fidelity":r.get("fidelity_level",""),"simulation_method":r.get("simulation_method",""),"tmm_usable_for_training":r.get("usable_for_training",""),"topology_family":g.get("topology_family",""),"candidate_id_primary":g.get("candidate_id_primary",""),"is_nominal_geometry":g.get("is_nominal_geometry","<missing>"),"parent_nominal_geometry_id":g.get("parent_nominal_geometry_id",""),"provenance_count":g.get("provenance_count",""),"split":s.get("split","<missing>"),"split_source_stage":s.get("source_stage",""),"split_usable_for_training":s.get("usable_for_training","")})
    OUT.mkdir(parents=True,exist_ok=True)
    fields=list(joined[0]);write_csv(OUT/"nominal_join_audit.csv",joined,fields)
    tmm_true=[x for x in joined if str(x["is_nominal_geometry"]).lower()=="true"]
    tmm_false=[x for x in joined if str(x["is_nominal_geometry"]).lower()=="false"]
    geo_true=[r for r in geo if str(r.get("is_nominal_geometry","")).lower()=="true"]
    source_by_geom=defaultdict(Counter)
    for p in prov:source_by_geom[p.get("geometry_id","")][p.get("source_id","")]+=1
    eq_fields={"geometry_master": [x for x in ["parent_nominal_geometry_id","is_nominal_geometry","provenance_count","quality_status"] if x in geo[0]],"tolerance_samples": [x for x in ["parent_nominal_geometry_id","parent_nominal_geometry_hash","sample_id","sample_hash","source_id","scan_mode","error_bound_nm","sample_index","layer_error_vector_json"] if x in tol[0]],"tmm_nominal_metrics": [x for x in ["record_id","source_id","fidelity_level","simulation_method","usable_for_training","quality_status"] if x in tmm[0]],"split_assignments": [x for x in ["record_id","geometry_id","parent_group_id","split","simulation_method","source_stage","usable_for_training"] if x in spl[0]]}
    true_identity=[]
    for x in tmm_true:
        g=by_gid[x["geometry_id"]]; z=brief(g);z["tmm_record_id"]=x["record_id"];z["tmm_source_id"]=x["tmm_source_id"];z["tmm_fidelity"]=x["tmm_fidelity"];z["split"]=x["split"];z["provenance_source_counts"]=dict(source_by_geom[g["geometry_id"]]);true_identity.append(z)
    false_prov=Counter()
    for x in tmm_false:
        for source,n in source_by_geom[x["geometry_id"]].items(): false_prov[source]+=n
    true_with_tolerance=sum(any("basin" in s or "mc" in s or "bias" in s for s in source_by_geom[r["geometry_id"]]) for r in geo_true)
    false_dist={"topology":count([by_gid[x["geometry_id"]] for x in tmm_false],"topology_family"),"tmm_source":count(tmm_false,"tmm_source_id"),"fidelity":count(tmm_false,"tmm_fidelity"),"split":count(tmm_false,"split"),"parent_nominal_geometry_id_blank":sum(not x["parent_nominal_geometry_id"] for x in tmm_false),"parent_nominal_geometry_id_nonblank":sum(bool(x["parent_nominal_geometry_id"]) for x in tmm_false),"provenance_source_counts":dict(false_prov)}
    split_tmm=[x for x in spl if x.get("record_id") in tmm_by_gid or x.get("source_stage") in ("coarse","refined")]
    # Correct record identity check uses TMM record ids; no source-table role inference.
    tmm_ids={r["record_id"] for r in tmm}; split_tmm=[x for x in spl if x.get("record_id") in tmm_ids]
    trace={"builder":"scripts/build_mdc_ml_database_v1.py","introducing_commit":git("log","--format=%H","-1","--","scripts/build_mdc_ml_database_v1.py"),"is_nominal_write":{"line":77,"condition":"candidate in NOMINAL_IDS","nominal_ids_line":83,"nominal_ids":["EX_N3_L79_H45_C156","ZL1_N3_M3_L78_H46","ZL1_N3_M3_L79_H44_C316","BARE_GAN_AIR_450_XDIPOLE"]},"canonical_tmm":{"function":"build_tmm","lines":"109-119","input":"coarse metrics_all.csv plus refined metrics_refined.csv","canonicalization":"chosen[geometry_hash]; refined supersedes coarse","no_is_nominal_filter":True},"tolerance":{"function":"build_tolerance","lines":"121-128","separate_table":"tolerance_samples.csv","usable_for_training":"false"},"split":{"lines":"172-201","strategy":"grouped_parent_geometry_v1 constraint graph","tmm_assignment":"line 195, one assignment per canonical TMM record","tolerance_assignment":"line 196, separate rows usable_for_training=false","fdtd_assignment":"line 197, external_high_fidelity_validation"},"history":git("log","--oneline","--follow","--","scripts/build_mdc_ml_database_v1.py").splitlines()}
    summary={"audit_name":"MDC_DATABASE_NOMINAL_SEMANTIC_AUDIT_V1","head":git("rev-parse","HEAD"),"database_manifest":manifest,"schema_version":schema.get("schema_version"),"table_counts":{"geometry_master_rows":len(geo),"geometry_master_unique_geometry_hashes":len(geo_hashes),"tmm_nominal_rows":len(tmm),"tmm_nominal_unique_geometry_hashes":len(tmm_hashes),"tolerance_rows":len(tol),"fdtd_rows":len(fdtd)},"hash_join":{"intersection":len(tmm_hashes&geo_hashes),"tmm_left_missing_from_geometry":len(tmm_hashes-geo_hashes),"geometry_right_not_in_tmm":len(geo_hashes-tmm_hashes),"tmm_duplicate_hash_rows":len(tmm)-len(tmm_hashes),"tmm_tolerance_hash_overlap":len(tmm_hashes&tol_hashes),"tmm_fdtd_hash_overlap":len(tmm_hashes&fdtd_hashes)},"is_nominal_geometry_all_geometry_master":count(geo,"is_nominal_geometry"),"reference_marker_scope":{"geometry_master_true_rows":len(geo_true),"geometry_master_true_rows_with_tolerance_provenance":true_with_tolerance},"is_nominal_geometry_among_tmm_join":count(joined,"is_nominal_geometry"),"tmm_join":{"id_matched":sum(x["id_join_status"]=="matched" for x in joined),"hash_matched":sum(x["hash_join_status"]=="matched" for x in joined),"true_rows":true_identity,"false_distribution":false_dist},"equivalent_fields":eq_fields,"tolerance_boundary":{"tmm_source_distribution":count(tmm,"source_id"),"tmm_simulation_method_distribution":count(tmm,"simulation_method"),"tmm_usable_distribution":count(tmm,"usable_for_training"),"tolerance_usable_distribution":count(tol,"usable_for_training"),"tmm_record_id_overlap_tolerance_sample_id":len(tmm_ids & {r["sample_id"] for r in tol}),"tmm_rows_with_tolerance_source_id":sum("tolerance" in r.get("source_id","").lower() for r in tmm)},"split_trace":{"tmm_records_present":len(split_tmm),"tmm_records_missing_from_split":len(tmm_ids-{r["record_id"] for r in split_tmm}),"extra_split_records_matching_tmm":len({r["record_id"] for r in split_tmm}-tmm_ids),"tmm_split_counts":count(split_tmm,"split"),"tmm_source_stage_counts":count(split_tmm,"source_stage"),"global_split_audit":split_audit},"label_dictionary_names":[r["label_name"] for r in labels],"quality_audit":quality,"generation_trace":trace,"root_cause":{"classification":"B intended, C implementation defect","finding":"is_nominal_geometry is assigned by candidate-id membership in a four-item reference list, not by simulation/sample role. build_tmm independently canonically emits all 2688 coarse/refined TMM scan records without filtering this flag. The field therefore means reference-candidate identity only when candidate naming is reliable; it also propagates to tolerance geometries carrying a reference candidate_id, so it is not a safe global nominal-sample flag."}}
    (OUT/"nominal_identity_summary.json").write_text(json.dumps(summary,indent=2),encoding="utf-8")
    lines=["# MDC database nominal semantic audit v1","",f"HEAD: `{summary['head']}`. Database/schema: {manifest['database_version']}/{schema.get('schema_version')}.","","## Finding","", "`is_nominal_geometry` is not the canonical definition of a nominal TMM sample. The builder writes it as `candidate in NOMINAL_IDS` (line 77), while `build_tmm` independently canonicalizes every coarse/refined scan geometry by geometry hash (lines 109-119) and writes all 2,688 rows to `tmm_nominal_metrics.csv` without consulting that flag.","", "The field was intended as a curated reference-candidate marker (B), but its implementation also applies to tolerance geometries that retain a reference candidate id. Therefore it is unsafe as a global physical nominal/perturbation predicate (C implementation defect).", "", "## Counts","", f"- geometry_master: {len(geo)} rows / {len(geo_hashes)} unique hashes.",f"- tmm_nominal_metrics: {len(tmm)} rows / {len(tmm_hashes)} unique hashes.",f"- TMM→geometry hash intersection: {len(tmm_hashes&geo_hashes)}; TMM left missing: {len(tmm_hashes-geo_hashes)}; geometry hashes not in TMM: {len(geo_hashes-tmm_hashes)}.",f"- `is_nominal_geometry` among all geometry rows: {count(geo,'is_nominal_geometry')}; among the canonical TMM join: {count(joined,'is_nominal_geometry')}.","", "## Two true canonical-TMM rows","", "| candidate | topology | geometry_id | H/L/C-or-center | layers / total nm | source / split |","|---|---|---|---|---|---|"]
    for r in true_identity: lines.append(f"| {r['candidate_id_primary']} | {r['topology_family']} | {r['geometry_id']} | H={r['H_nm']}, L={r['L_nm']}, C={r['C_nm'] or '-'}, center={r['effective_central_L_thickness_nm'] or '-'} | {r['physical_layer_count']} / {r['total_thickness_nm']} | {r['tmm_source_id']} / {r['split']} |")
    lines += ["", "## Tolerance and split boundary","", f"- Canonical TMM sources: {count(tmm,'source_id')}; all carry simulation_method TMM and usable_for_training true.", f"- Tolerance sources are stored only in tolerance_samples.csv ({len(tol)} rows), with usable_for_training false. TMM record-id overlap with tolerance sample IDs: 0; TMM rows with tolerance source id: 0.", f"- Existing split contains all {len(split_tmm)} canonical TMM records: {count(split_tmm,'split')}. Assignment is direct per TMM record, but its constraint graph also includes tolerance parent links to prevent geometry leakage.", "", "## Minimal repair options (not implemented)", "", "1. Recommended C — make `tmm_nominal_metrics` the canonical nominal-sample fact table in task views; use geometry_master only for geometry joins. No reinterpretation of existing `is_nominal_geometry`; no database-v1 rebuild required for a task view. Add explicit join semantics to a future schema/report revision.", "2. A — retain the field as curated-reference identity and introduce `sample_role` / `is_nominal_tmm_sample` in a v1.1 database rebuild. This preserves existing field semantics; requires schema version bump and database regeneration, but does not change tolerance/FDTD boundaries.", "3. B — regenerate `is_nominal_geometry` for all 2,688 canonical TMM hashes. Not recommended because it changes the field's current curated-reference meaning and still fails to distinguish TMM nominal rows from tolerance geometries sharing candidate identifiers; requires a schema bump and rebuild.", "", "## Recommendation","", "Use `tmm_nominal_metrics` + its `simulation_method=TMM`, `usable_for_training=true`, and canonical record identity as the nominal training universe. Do not filter on `geometry_master.is_nominal_geometry`. Before future release, add an explicit sample-role field and correct the reference-marker name."]
    REPORT.parent.mkdir(parents=True,exist_ok=True);REPORT.write_text("\n".join(lines)+"\n",encoding="utf-8")
    print(json.dumps({"status":"PASS","tmm_rows":len(tmm),"tmm_true_marker_rows":len(tmm_true),"root_cause":"B intended, C implementation defect"},indent=2))
if __name__=="__main__":main()
